NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/192-168-1-78-7778.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/192-168-1-78-7778.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/192-168-1-78-7778.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/192-168-1-78-7778.pem
    OrganizationalUnitIdentifier: orderer